# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha

    working_directory: ~/code

    environment:
      JVM_OPTS: -Xmx4G

    steps:
      - checkout
      - run: echo "Build process is started 👯"

      - run:
          name: Create debug.keystore.jks
          command: echo $DEBUG_KEYSTORE_BASE64 | base64 -di > $debugKeyStore
      - run:
          name: Create release.keystore.jks
          command: echo $RELEASE_KEYSTORE_BASE64 | base64 -di > $releaseKeyStore

      - run:
          name: Create keystore.properties
          command: printf 'debugKeyAlias=%s\ndebugKeyPassword=%s\ndebugKeyStore=%s\ndebugStorePassword=%s\nreleaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s' $debugKeyAlias $debugKeyPassword $debugKeyStore $debugStorePassword $releaseKeyAlias $releaseKeyPassword $releaseKeyStore $releaseStorePassword > keystore.properties

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run:
          name: Run tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results
          destination: test-results/
      - run:
          name: Initial build
          command: ./gradlew clean assembleRelease --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - run:
          name: "Install Firebase SDK"
          command: curl -sL https://firebase.tools | bash
      - run:
          name: "Deploy Android APK to Firebase App Distribution."
          command: firebase appdistribution:distribute --app=${ANDROID_APP_ID} --groups=android-testers --token=${FIREBASE_TOKEN} app/build/outputs/apk/release/app-release.apk

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop